name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Selecionar subscription
        run: az account set --subscription 8565d32b-e115-4870-9c70-f0fdb4235689

      - name: Deploy para Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: front-testes001
          package: .   # publica tudo (server.js, package.json e frontend/)
          slot-name: production
